DROP DATABASE IF EXISTS userInfo;
CREATE DATABASE userInfo;
USE userInfo;

CREATE TABLE list (
  id INT AUTO_INCREMENT,
  name VARCHAR(225) NOT NULL,
  email VARCHAR(225) NOT NULL,
  password VARCHAR(225) NOT NULL,
  phone VARCHAR(225) NOT NULL,
  address VARCHAR(225) NOT NULL,
  creditCard VARCHAR(225) NOT NULL,
  PRIMARY KEY (id)
);